exp_dir: /mnt/data/liuhongyu/rg/results/iuxray
dataset_dir: /mnt/data/liuhongyu/rg
ckpt_zoo_dir: /mnt/data/liuhongyu/rg/checkpoints
# venv_path: venv/bin/activate  # If using a SLURM cluster, uncomment this line.
seed: 9223
trial: 9223
devices: 1
num_nodes: 1
num_workers: 6
strategy: 'auto'

module: cvt2distilgpt2_iu_x_ray_chen
definition: CvT2DistilGPT2IUXRayChen

encoder_lr: 5e-5
decoder_lr: 5e-4
mbatch_size: 12  # 4 * 4 devices = mini-batch size of 16.
every_n_epochs: 1

monitor: 'val_chen_cider'
monitor_mode: 'max'
precision: 16
decoder_max_len: 128
num_test_beams: 4
max_epochs: 100
save_top_k: 3

enable_progress_bar: True
weights_summary: 'full'

early_stopping: True
patience: 10
min_delta: 1e-4
deterministic: False

# CUDA_VISIBLE_DEVICES=3 dlhpcstarter -t iu_x_ray_ot -c config/train_iu_x_ray_chen_cvt2distilgpt2.yaml --stages_module stages --train